"""Parent-chapter context for indexed verses.

Several Charaka chapters open with a bare title verse --

    "We shall now expound the chapter entitled 'The Quest for Longevity.'"

-- that names the chapter's subject without stating any of its content. A
question like "how can one live a long, healthy life?" is semantically *about*
chapter 1, yet the only verse in that chapter whose text mentions longevity is
that title line. Embedding ``text_english`` alone therefore leaves short
title-like verses with almost no topical signal, which showed up as retrieval
misses on exactly those chapters.

This module builds the parent-context prefix that both the vector index and the
BM25 index prepend, so the two halves of hybrid search see the same signal.

Design note
-----------
The prefix is applied to what gets **embedded and BM25-indexed**, never to the
``documents`` string that Chroma stores and the app displays. ``text_english``
must stay clean because it is what the citation cards, the attribution node and
the synthesis prompt read; injecting a "Chapter: ..." header there would show up
in the UI as part of the verse.

Titles come from ``reference/chapter_titles.json``, generated by
``scripts/build_chapter_titles.py`` from the corpus itself -- nothing here
invents content. Chapters with no title verse (only ``sutrasthana/20``, which
opens with a numbered list) fall back to their condition/category metadata.
"""

import json
import re
from functools import lru_cache
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
TITLES_PATH = BACKEND / "reference" / "chapter_titles.json"

_HERB_KEY_RE = re.compile(r"[^a-z0-9]+")


def herb_key(herb: str) -> str:
    """Chroma metadata key for one herb, e.g. 'ashwagandha' -> 'herb_ashwagandha'.

    Slugged so a herb name containing a space or punctuation cannot produce an
    illegal field name. Defined here so the index builder and the retriever can
    never disagree about the key for the same herb.
    """
    slug = _HERB_KEY_RE.sub("_", str(herb).strip().lower()).strip("_")
    return f"herb_{slug}" if slug else ""


@lru_cache(maxsize=1)
def load_chapter_titles() -> dict[str, str]:
    """Map "sthana/chapter" -> chapter title. Empty if the file is absent.

    Tolerating a missing file keeps retrieval working on a fresh clone that has
    not run ``scripts/build_chapter_titles.py`` yet; verses simply fall back to
    condition/category context.
    """
    if not TITLES_PATH.is_file():
        return {}
    with open(TITLES_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def chapter_key(sthana, chapter) -> str:
    return f"{sthana}/{int(chapter)}"


def chapter_context(record: dict) -> str:
    """Parent-context prefix for one corpus record. Never ends without a space.

    Falls back through title -> condition/category -> nothing, so every verse in
    a chapter shares the same prefix and BM25 gains the chapter terms too.
    """
    titles = load_chapter_titles()
    key = chapter_key(record.get("sthana"), record.get("chapter") or 0)

    bits = []
    title = titles.get(key)
    if title:
        bits.append(title)

    # Chroma stores missing enum values as the string "none"; treat that and
    # empty as absent so the prefix never reads "Category: none".
    seen = {b.strip().lower() for b in bits}
    for field in ("traditional_condition", "category_tag"):
        raw = record.get(field)
        if not raw or raw == "none":
            continue
        pretty = str(raw).replace("_", " ").strip()
        # Skip a tag already implied by the title so the prefix does not repeat
        # the same words twice.
        if pretty.lower() in seen:
            continue
        seen.add(pretty.lower())
        bits.append(pretty)

    if not bits:
        return ""
    return "Charaka Samhita, " + key + ": " + "; ".join(bits) + ". "


def embed_document(record: dict) -> str:
    """The exact string to embed and BM25-index for one record.

    Kept in one place so the vector index and the BM25 index can never drift
    apart in what they consider a verse's text.
    """
    text = (record.get("text_english") or "").strip()
    return chapter_context(record) + text


# --- freshness ---------------------------------------------------------------
#
# The index is regenerated from the corpus rather than committed, so a stale
# index is a real failure mode: edit the corpus, forget to rebuild, and the app
# silently answers from the old vectors with no error anywhere. The corpus hash
# is recorded in the Chroma collection at build time and re-checked on startup,
# which turns "silently stale" into a visible warning on /healthz.

CORPUS_PATH = BACKEND / "processed" / "charaka_structured.json"


def corpus_sha256(path=None) -> str:
    """SHA-256 of the processed corpus file, or "" if it is absent."""
    import hashlib

    target = path or CORPUS_PATH
    if not Path(target).is_file():
        return ""
    digest = hashlib.sha256()
    with open(target, "rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def index_freshness(collection=None) -> dict:
    """Compare the on-disk corpus against the hash stored in the index.

    Returns a dict suitable for /healthz:

        {"status": "ok"|"stale"|"unknown", "corpus_sha256": ..., "index_sha256": ...,
         "detail": "..."}

    ``unknown`` means the index predates this bookkeeping and carries no hash,
    which is not an error -- it just cannot be verified, and callers should not
    fail a health check over it.
    """
    current = corpus_sha256()
    result = {
        "status": "unknown",
        "corpus_sha256": current,
        "index_sha256": None,
        "verse_count": None,
        "detail": "index carries no corpus hash; rebuild to enable verification",
    }
    if collection is None:
        return result
    try:
        stored = (collection.metadata or {}).get("corpus_sha256")
        result["index_sha256"] = stored
        result["verse_count"] = collection.count()
    except Exception as exc:  # noqa: BLE001 - never break a health check
        result["detail"] = f"could not read index metadata: {exc}"
        return result

    if not stored:
        return result
    if not current:
        result["status"] = "unknown"
        result["detail"] = "corpus file missing; cannot verify the index"
        return result
    if stored == current:
        result["status"] = "ok"
        result["detail"] = "index matches the processed corpus"
    else:
        result["status"] = "stale"
        result["detail"] = (
            "corpus has changed since the index was built - run "
            "`python scripts/transform.py && python scripts/build_chapter_titles.py "
            "&& python scripts/build_vector_store.py`"
        )
    return result