const HERB_IMAGE_FILES: Record<string, string> = {
  ajwain: "Ajwain (Trachyspermum ammi).jpg",
  amalaki: "Indian Gooseberry (Amla).jpg",
  amlavetasa: "Garcinia morella Alwis.jpg",
  arka: "Calotropis gigantea 3012.jpg",
  asafoetida: "Ferula assa-foetida Zapaliczka cuchnąca 2020-07-31 04.jpg",
  ashwagandha: "Ashwagandha (Withania somnifera).jpg",
  atibala: "Indian abutilon Abutilon indicum 3266.jpg",
  bael: "Bael (Aegle marmelos) leaf.jpg",
  "garden radish": "Raphanus sativus kz01.jpg",
  bala: "Sida cordifolia (Bala) in Hyderabad, AP W IMG 9420.jpg",
  bhringaraj: "Eclipta prostrata (19240).jpg",
  bibhitaki: "Terminalia bellirica.jpg",
  "black pepper": "Black Pepper (Piper nigrum) fruits.jpg",
  brahmi: "Starr 010818-0007 Bacopa monnieri.jpg",
  brihati: "Solanum anguivi - Forest Bitterberry, African Eggplant, Cheruchunda 2.jpg",
  cardamom: "Elettaria cardamomum Capsules and seeds.jpg",
  castor: "Ricinus communis in Sicily 2024.jpg",
  celery: "2023-06-22 Apium graveolens (Wild Celery), Elswick, Northumberland 4.jpg",
  chavya: "Piper chaba BotGardBln1105Z.JPG",
  cinnamon: "Cinnamomum verum spices.jpg",
  cumin: "Cuminum cyminum-2-market-yercaud-salem-India.JPG",
  daruharidra: "BerberisAculeata.jpg",
  devadaru: "Cedrus deodara India02.jpg",
  dhanyaka: "(MHNT) Coriandrum sativum - inflorescence.jpg",
  eranda: "Ricinus communis in Sicily 2024.jpg",
  fennel: "Fennel seeds 01.jpg",
  fenugreek: "Trigonella foenum-graecum kz04.jpg",
  gandhatruna: "Cymbopogon citratus.jpg",
  garlic: "Garlic.jpg",
  ginger: "Ginger Plant vs.jpg",
  gokarna: "Hygrophila auriculata 05.JPG",
  gokshura: "Tribulus terrestris - Dghoumes National Park.jpg",
  guduchi: "Tinospora cordifolia (3052488338).jpg",
  guggulu: "Commiphora-wightii-resin.jpg",
  haritaki: "Haritaki (Terminalia chebula) fruits.jpg",
  jambul: "Syzygium cumini plant.jpg",
  jatamansi: "Nardostachys grandiflora.jpg",
  jivanti: "Leptadenia reticulata climber.JPG",
  kakamachi: "Solanum nigrum fruits.JPG",
  kantakari: "Solanum xanthocarpum 9909.jpg",
  karkaru: "Lagenaria siceraria kz02.jpg",
  katphala: "Myrica esculenta.jpg",
  karpura: "Cinnamomum camphora Vergelegen.jpg",
  kataka: "Strychnos potatorum 5.jpg",
  ketaki: "Pandanus odorifer - Kewda 3.jpg",
  khadira: "Acacia catechu 05.JPG",
  khasa: "Vetiveria zizanoides dsc07810.jpg",
  kustha: "Saussurea costus on way from Gangria to Hemkund at Valley of Flowers National Park - during LGFC - VOF 2019 (6).jpg",
  kutaja: "Holarrhena pubescens 1DS-II 3-2828.jpg",
  leadwort: "Plumbago zeylanica 01.JPG",
  liquorice: "Glycyrrhiza glabra kz01.jpg",
  lodhra: "Symplocos lucida SZ24.png",
  "long pepper": "Long pepper plant(Piper longum).JPG",
  manjistha: "Rubia cordifolia.jpg",
  "marking nut": "Semecarpus anacardium 02.jpg",
  moringa: "Moringa oleifera flower.jpg",
  mustard: "Brassica nigra - March 2024 - Sarah Stierch 02.jpg",
  musta: "Cyperus rotundus in Split, Croatia 20230530 01.jpg",
  nagakesara: "Mesua ferrea fruit Agumbe.jpg",
  nagarmotha: "CyperusScariosus 6259.JPG",
  nimba: "Neem (Azadirachta indica) in Hyderabad W IMG 6976.jpg",
  onion: "Red onion.jpg",
  padmakesara: "Nelumno nucifera open flower - botanic garden adelaide2.jpg",
  palasha: "STS 001 Butea monosperma.jpg",
  patala: "Stereospermum chelonoides Blanco2.252-cropped.jpg",
  patola: "Trichosanthes cucumerina.jpg",
  pomegranate: "Pomegranate fruit - whole and piece with arils.jpg",
  priyangu: "Callicarpa macrophylla.jpg",
  punarnava: "Boerhavia diffusa 2.jpg",
  raktachandana: "Pterocarpus santalinus 14.JPG",
  rasna: "Starr 080208-2543 Pluchea carolinensis.jpg",
  sandalwood: "Sandalwood harvest.jpg",
  sankhapushpi: "Convolvulus prostratus kz01.jpg",
  sariva: "Hemidesmus indicus 01.JPG",
  shalparni: "Desmodium gangeticum plant.jpg",
  shatapushpa: "Anethum graveolens20090812 475.jpg",
  shatavari: "Asparagus racemosus.JPG",
  shirisha: "Albizia lebbeck MHNT.BOT.2015.2.45.jpg",
  stira: "Desmodium gangeticum plant.jpg",
  surasa: "Tulsi or Tulasi Holy basil.jpg",
  tagara: "Valeriana officinalis kz05.jpg",
  trapusha: "Cucumis sativus 0001.JPG",
  trikatu: "Long pepper plant(Piper longum).JPG",
  tulsi: "Ocimum tenuiflorum 3 09 2012.JPG",
  turmeric: "Curcuma longa roots.jpg",
  turpeth: "Operculina turpethum (Nisottar) in Kawal, AP W IMG 2211.jpg",
  utpala: "Blue lotus (Nymphaea sp).jpg",
  vacha: "Acorus calamus 002.JPG",
  vasa: "Malabar nut tree - Unknown - 19 1927 2 43.jpg",
  vasaka: "Justicia adhatoda 1.jpg",
  vidanga: "Embelia ribes.jpg",
  yavani: "Ajwain.JPG",
};

export const HERB_IMAGE_COUNT = Object.keys(HERB_IMAGE_FILES).length;

export function herbImageUrl(name: string): string | null {
  const file = HERB_IMAGE_FILES[name.toLowerCase()];
  if (!file) return null;
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=400`;
}